inherit_from: configs/64res/cars_64.yaml
training:
  out_dir:  out/cars64_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/giraffe/models/checkpoint_compcars64-e85060a0.pt
