inherit_from: configs/64res/church_64.yaml
training:
  out_dir:  out/church64_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/giraffe/models/checkpoint_church64-03c09878.pt
