inherit_from: configs/256res/church_256.yaml
training:
  out_dir:  out/church256_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/giraffe/models/checkpoint_church256-ebd63480.pt
