data:
  path:  data/clevr2/images/*.png
  fid_file: data/clevr2/fid_files/clevr2_256.npz
  img_size: 256
model:
  background_generator_kwargs:
    rgb_out_dim: 256
  bounding_box_generator_kwargs: #f = 0.2378777237835723 
    scale_range_min: [0.17, 0.17, 0.17]
    scale_range_max: [0.17, 0.17, 0.17]
    translation_range_min: [-0.713, -0.713, 0]
    translation_range_max: [0.713, 0.713, 0]
    rotation_range: [0., 0.]
    n_boxes: 2
    prior_npz_file:  data/clevr2/prior/clevr2_256.npz
    z_level_plane: 0.1665
    object_on_plane: True
  generator_kwargs:
    range_v: [0.33333, 0.33333]
  neural_renderer_kwargs:
    input_dim: 256
    n_feat: 256
  decoder_kwargs:
    rgb_out_dim: 256
training:
  out_dir:  out/clevr2256
  learning_rate: 0.00025
rendering:
  render_program: ['render_add_clevr10', 'render_add_clevr6', 'object_translation_circle']
