inherit_from: configs/256res/clevr2345_256.yaml
training:
  out_dir:  out/clevr2345256_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/giraffe/models/checkpoint_clevr2345256-aa03cd59.pt