inherit_from: configs/256res/clevr2_256.yaml
training:
  out_dir:  out/clevr2256_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/giraffe/models/checkpoint_clevr2256-96bd7074.pt
