inherit_from: configs/256res/ffhq_256.yaml
training:
  out_dir:  out/ffhq256_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/giraffe/models/checkpoint_ffhq256-fa488759.pt